meters:
  Gottfried_Lieferung:
    GPIO: 21
    Imp: 10000
  Gottfried_Bezug:
    GPIO: 20
    Imp: 10000
  Gregor:
    GPIO: 13
    Imp: 1000
  Marianna:
    GPIO: 5
    Imp: 1000
  Uli:
    GPIO: 7
    Imp: 1000
db_con: "sqlite:///./data/pulse.sqlite"


