# Meter definition
# db_table: # the database table (=Sqlalchemy type) into which this metric shall be written
#  - Pulse (S0, count pulses per unit of energy)
#  - Power (read out current power in W),
#  - CumulativePower (read out increasing counter in Wh)
# GPIO: GPIO port for Pulse
# Imp: Number of pulses per kWh for Pulse
# modbus: modbus register for Power/Cumulative Power
# modbus_type: data type of the modbus register, e.g. U64 (unsigned 64-bit),  S32 (signed 32 bit), ...
# ip: IP address for modbus
meters:
  Gottfried_Lieferung:
    db_table: Pulse
    GPIO: 21
    Imp: 1000
  Gottfried_Bezug:
    db_table: Pulse
    GPIO: 20
    Imp: 1000
  Gregor:
    db_table: Pulse
    GPIO: 13
    Imp: 1000
  Marianna:
    db_table: Pulse
    GPIO: 5
    Imp: 1000
  Uli:
    db_table: Pulse
    GPIO: 7
    Imp: 1000
  Sunny_Tripower_Gesamtertrag:
    description: "Gesamtertrag Wechselrichter (Wh)"
    db_table: CumulativePower
    modbus: 30513
    modbus_type: U64
    ip: 192.168.193.147
  Sunny_Island_Batterieleistung:
    description: "Leistung Speichersystem, negativ wenn laden (Wh)"
    db_table: Power
    modbus: 30775
    modbus_type: S32
    ip: 192.168.193.156
  Sunny_Island_Netzbezug:
    description: "Netzbezug gesamt (Wh)"
    db_table: CumulativePower
    modbus: 30581
    modbus_type: U32
    ip: 192.168.193.156
  Sunny_Island_Einspeisung:
    description: "Netzeinspeisung gesamt (Wh)"
    db_table: CumulativePower
    modbus: 30583
    modbus_type: U32
    ip: 192.168.193.156
  Sunny_Island_Ladezustand:
    description: "Ladezustand des Akkus (%)"
    db_table: null # don't save to db
    modbus: 30845
    modbus_type: U32
    ip: 192.168.193.156
  Sunny_Island_Netzbezug_Leistung:
    description: "Netzbezug momentan (W)"
    db_table: null # don't save to db
    modbus: 30865
    modbus_type: S32
    ip: 192.168.193.156
  Sunny_Island_Einspeisung_Leistung:
    description: "Einspeisung momentan (W)"
    db_table: null # don't save to db
    modbus: 30867
    modbus_type: S32
    ip: 192.168.193.156
db_con: "sqlite:///./data/pulse.sqlite"
# interval for polling modbus interfaces in seconds
interval: 5
